# LISTS ARE THE COLLECTION OF ORDERED AND MUTABLE DATA
# LISTS ARE WRITTEN INSIDE THE SQUARED BRACKETS
# THE VALUE INSIDE A LIST IS SEPARATED BY ,
# MUTABLE MEANS ONCE CREATED , THEY CAN BE CHANGED
# MULTIPLE DATAYPES CAN BE WRITTEN INSIDE A LIST

fruits=["mango","apple","banana"]
print(fruits)

random = ["sourav", 90 , 90.88 , False]
print(random[3])  # IT WILL PRINT THE VALUE ON THE THIRD INDEX (90.88)
print(random[0])  # IT WILL PRINT THE VALUE AT THE ZERO INDEX (sourav)


